In [1]:
# Check environment
!conda info
# active environment should be WM_ML

     active environment : WM_ML
    active env location : /opt/anaconda3/envs/WM_ML
            shell level : 1
       user config file : /Users/jilliancheck/.condarc
 populated config files : /Users/jilliancheck/.condarc
          conda version : 24.11.3
    conda-build version : 24.5.1
         python version : 3.12.4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.11.3=0
                          __osx=15.0=0
                          __unix=0=0
       base environment : /opt/anaconda3  (writable)
      conda av data dir : /opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          /Users/jilliancheck/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /Users/jilliancheck/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.11.3 requests/2.32.2 CPython/3.12.4 Darwin/24.0.0 OSX/15.0 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 aau/0.4.4 c/87g31VdAyYauzBh-6vDWsA s/tBPb2jiRuw0jTXWxDnqnfA e/iqJlpZGrtHaR8kb0N0_eqg
                UID:GID : 501:20
             netrc file : None
           offline mode : False

In [28]:
import pandas as pd
from sklearn.model_selection import train_test_split

### RTMA only data

In [29]:
RTMA_df = pd.read_csv('/Users/jilliancheck/OneDrive - Michigan State University/Documents/Work/White mold/Modeling/jupyter notebooks/WM train test data Fall 24/RTMA_23_df.csv')

# Create row shading 

row_shading = RTMA_df['canopy_avg'] * RTMA_df['spacing (m)']
insert_index = RTMA_df.columns.get_loc('target') + 1  # Insert after col1
RTMA_df.insert(insert_index, 'row_shading', row_shading)

# Remove or encode categorical data

RTMA_df = RTMA_df.drop(columns=['index', 'Date', 'crop', 'spacing (m)', 'canopy_avg'])
RTMA_df['soil type'].replace(['sand', 'loamy sand', 'loam'], [0, 1, 2], inplace=True)

display(RTMA_df)

/var/folders/ht/9fl18sfx147g3y41wft40g0c0000gn/T/ipykernel_9790/2140331121.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  RTMA_df['soil type'].replace(['sand', 'loamy sand', 'loam'], [0, 1, 2], inplace=True)
/var/folders/ht/9fl18sfx147g3y41wft40g0c0000gn/T/ipykernel_9790/2140331121.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  RTMA_df['soil type'].replace(['sand', 'loamy sand', 'loam'], [0, 1, 2], inplace=True)

,soil type,target,row_shading,MA_MeanAT,MA_MeanDP,MA_MeanRH,MA_MeanWS,MA_MeanRH86,MA_MeanATD,MA_MeanRF_IBM,...,MA_MinWS,MA_MinRH86,MA_MinATD,MA_SumAT,MA_SumDP,MA_SumRH,MA_SumWS,MA_SumRH86,MA_SumATD,MA_SumRF_IBM
0,2,1,36.8182,21.311806,16.241250,75.237500,2.089853,0.381944,0.788889,0.130278,...,0.362963,0.033333,0.333333,15344.5,11693.7,54171.0,1504.694444,275,568,93.8
1,2,0,37.0766,22.052639,16.547500,73.497083,2.072184,0.344444,0.718056,0.170556,...,0.437963,0.000000,0.133333,15877.9,11914.2,52917.9,1491.972222,248,517,122.8
2,1,1,47.2005,21.771667,16.786944,75.555556,2.747222,0.355556,0.781944,0.120278,...,0.869444,0.033333,0.433333,15675.6,12086.6,54400.0,1978.000000,256,563,86.6
3,1,1,47.3739,20.734306,15.819861,75.873889,2.363272,0.377778,0.837500,0.107778,...,0.623148,0.033333,0.500000,14928.7,11390.3,54629.2,1701.555556,272,603,77.6
4,1,1,44.9871,21.710972,16.732222,75.667778,2.523187,0.356944,0.752778,0.095139,...,0.661111,0.000000,0.266667,15631.9,12047.2,54480.8,1816.694444,257,542,68.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,1,1,74.3736,20.150833,15.310278,76.240278,2.629051,0.415278,0.848611,0.218194,...,0.777778,0.000000,0.333333,14508.6,11023.4,54893.0,1892.916667,299,611,157.1
143,1,1,82.0096,20.150833,15.310278,76.240278,2.629051,0.415278,0.848611,0.218194,...,0.777778,0.000000,0.333333,14508.6,11023.4,54893.0,1892.916667,299,611,157.1
144,1,0,50.1381,20.150833,15.310278,76.240278,2.629051,0.415278,0.848611,0.218194,...,0.777778,0.000000,0.333333,14508.6,11023.4,54893.0,1892.916667,299,611,157.1
145,1,1,73.5072,20.248333,15.631806,77.112500,2.642747,0.412500,0.848611,0.185278,...,0.890741,0.000000,0.400000,14578.8,11254.9,55521.0,1902.777778,297,611,133.4
146,1,0,49.7811,20.248333,15.631806,77.112500,2.642747,0.412500,0.848611,0.185278,...,0.890741,0.000000,0.400000,14578.8,11254.9,55521.0,1902.777778,297,611,133.4

In [40]:
# Save target as y data

ydat_RTMA = RTMA_df['target']
display(ydat_RTMA)

# Save everything else as x data

xdat_RTMA = RTMA_df.drop(columns =['target'])
display(xdat_RTMA)

0      1
1      0
2      1
3      1
4      1
      ..
142    1
143    1
144    0
145    1
146    0
Name: target, Length: 147, dtype: int64

,soil type,row_shading,MA_MeanAT,MA_MeanDP,MA_MeanRH,MA_MeanWS,MA_MeanRH86,MA_MeanATD,MA_MeanRF_IBM,MA_MaxAT,...,MA_MinWS,MA_MinRH86,MA_MinATD,MA_SumAT,MA_SumDP,MA_SumRH,MA_SumWS,MA_SumRH86,MA_SumATD,MA_SumRF_IBM
0,2,36.8182,21.311806,16.241250,75.237500,2.089853,0.381944,0.788889,0.130278,26.476667,...,0.362963,0.033333,0.333333,15344.5,11693.7,54171.0,1504.694444,275,568,93.8
1,2,37.0766,22.052639,16.547500,73.497083,2.072184,0.344444,0.718056,0.170556,27.763333,...,0.437963,0.000000,0.133333,15877.9,11914.2,52917.9,1491.972222,248,517,122.8
2,1,47.2005,21.771667,16.786944,75.555556,2.747222,0.355556,0.781944,0.120278,26.343333,...,0.869444,0.033333,0.433333,15675.6,12086.6,54400.0,1978.000000,256,563,86.6
3,1,47.3739,20.734306,15.819861,75.873889,2.363272,0.377778,0.837500,0.107778,25.513333,...,0.623148,0.033333,0.500000,14928.7,11390.3,54629.2,1701.555556,272,603,77.6
4,1,44.9871,21.710972,16.732222,75.667778,2.523187,0.356944,0.752778,0.095139,26.840000,...,0.661111,0.000000,0.266667,15631.9,12047.2,54480.8,1816.694444,257,542,68.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,1,74.3736,20.150833,15.310278,76.240278,2.629051,0.415278,0.848611,0.218194,25.456667,...,0.777778,0.000000,0.333333,14508.6,11023.4,54893.0,1892.916667,299,611,157.1
143,1,82.0096,20.150833,15.310278,76.240278,2.629051,0.415278,0.848611,0.218194,25.456667,...,0.777778,0.000000,0.333333,14508.6,11023.4,54893.0,1892.916667,299,611,157.1
144,1,50.1381,20.150833,15.310278,76.240278,2.629051,0.415278,0.848611,0.218194,25.456667,...,0.777778,0.000000,0.333333,14508.6,11023.4,54893.0,1892.916667,299,611,157.1
145,1,73.5072,20.248333,15.631806,77.112500,2.642747,0.412500,0.848611,0.185278,25.470000,...,0.890741,0.000000,0.400000,14578.8,11254.9,55521.0,1902.777778,297,611,133.4
146,1,49.7811,20.248333,15.631806,77.112500,2.642747,0.412500,0.848611,0.185278,25.470000,...,0.890741,0.000000,0.400000,14578.8,11254.9,55521.0,1902.777778,297,611,133.4

In [42]:
# Read out data

xdat_RTMA.to_csv('/Users/jilliancheck/Library/CloudStorage/OneDrive-MichiganStateUniversity/Documents/Work/White mold/Modeling/jupyter notebooks/!Finalizing - 2024/Unprocessed data for HPCC/x_dat_RTMA_HPCC.csv', index=False)
ydat_RTMA.to_csv('/Users/jilliancheck/Library/CloudStorage/OneDrive-MichiganStateUniversity/Documents/Work/White mold/Modeling/jupyter notebooks/!Finalizing - 2024/Unprocessed data for HPCC/y_dat_RTMA_HPCC.csv', index=False)

### RMTA and SM/ST data

In [48]:
LX_df = pd.read_csv('/Users/jilliancheck/OneDrive - Michigan State University/Documents/Work/White mold/Modeling/jupyter notebooks/WM train test data Fall 24/RTMA_LX_23_df.csv')

# Create row shading 

row_shading = LX_df['canopy_avg'] * LX_df['spacing (m)']
insert_index = LX_df.columns.get_loc('target') + 1  # Insert after col1
LX_df.insert(insert_index, 'row_shading', row_shading)

# Remove or encode categorical data

LX_df = LX_df.drop(columns=['index', 'Date', 'crop', 'spacing (m)', 'canopy_avg'])
LX_df['soil type'].replace(['sand', 'loamy sand', 'loam'], [0, 1, 2], inplace=True)

display(LX_df)

/var/folders/ht/9fl18sfx147g3y41wft40g0c0000gn/T/ipykernel_9790/2793805911.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  LX_df['soil type'].replace(['sand', 'loamy sand', 'loam'], [0, 1, 2], inplace=True)
/var/folders/ht/9fl18sfx147g3y41wft40g0c0000gn/T/ipykernel_9790/2793805911.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  LX_df['soil type'].replace(['sand', 'loamy sand', 'loam'], [0, 1, 2], inplace=True)

,soil type,target,row_shading,MA_MeanAT,MA_MeanDP,MA_MeanRH,MA_MeanWS,MA_MeanRH86,MA_MeanATD,MA_MeanRF_IBM,...,MA_MinST_IR,MA_SumAT,MA_SumDP,MA_SumRH,MA_SumWS,MA_SumRH86,MA_SumATD,MA_SumRF_IBM,MA_SumSM_IR,MA_SumST_IR
0,2,1,36.8182,21.311806,16.241250,75.237500,2.089853,0.381944,0.788889,0.130278,...,20.255709,15344.5,11693.7,54171.0,1504.694444,275,568,93.8,3117.916742,4970.720308
1,2,0,37.0766,22.052639,16.547500,73.497083,2.072184,0.344444,0.718056,0.170556,...,20.623318,15877.9,11914.2,52917.9,1491.972222,248,517,122.8,5779.277750,9208.189375
2,1,1,47.2005,21.771667,16.786944,75.555556,2.747222,0.355556,0.781944,0.120278,...,21.468948,15675.6,12086.6,54400.0,1978.000000,256,563,86.6,791.432858,1333.557258
3,1,1,47.3739,20.734306,15.819861,75.873889,2.363272,0.377778,0.837500,0.107778,...,20.276167,14928.7,11390.3,54629.2,1701.555556,272,603,77.6,2934.870167,4677.423125
4,1,1,44.9871,21.710972,16.732222,75.667778,2.523187,0.356944,0.752778,0.095139,...,20.732416,15631.9,12047.2,54480.8,1816.694444,257,542,68.5,4805.097617,7620.721658
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,1,1,74.3736,20.150833,15.310278,76.240278,2.629051,0.415278,0.848611,0.218194,...,14.166283,14508.6,11023.4,54893.0,1892.916667,299,611,157.1,13358.500900,11729.418411
143,1,1,82.0096,20.150833,15.310278,76.240278,2.629051,0.415278,0.848611,0.218194,...,18.004157,14508.6,11023.4,54893.0,1892.916667,299,611,157.1,6795.649295,14399.740150
144,1,0,50.1381,20.150833,15.310278,76.240278,2.629051,0.415278,0.848611,0.218194,...,17.252178,14508.6,11023.4,54893.0,1892.916667,299,611,157.1,7254.873860,11434.259833
145,1,1,73.5072,20.248333,15.631806,77.112500,2.642747,0.412500,0.848611,0.185278,...,15.699848,14578.8,11254.9,55521.0,1902.777778,297,611,133.4,12298.577130,12884.937338
146,1,0,49.7811,20.248333,15.631806,77.112500,2.642747,0.412500,0.848611,0.185278,...,17.218818,14578.8,11254.9,55521.0,1902.777778,297,611,133.4,7132.674290,11481.784733

In [49]:
# Save target as y data

ydat_LX = LX_df['target']
display(ydat_LX)

# Save everything else as x data

xdat_LX = LX_df.drop(columns =['target'])
display(xdat_LX)

0      1
1      0
2      1
3      1
4      1
      ..
142    1
143    1
144    0
145    1
146    0
Name: target, Length: 147, dtype: int64

,soil type,row_shading,MA_MeanAT,MA_MeanDP,MA_MeanRH,MA_MeanWS,MA_MeanRH86,MA_MeanATD,MA_MeanRF_IBM,MA_MeanSM_IR,...,MA_MinST_IR,MA_SumAT,MA_SumDP,MA_SumRH,MA_SumWS,MA_SumRH86,MA_SumATD,MA_SumRF_IBM,MA_SumSM_IR,MA_SumST_IR
0,2,36.8182,21.311806,16.241250,75.237500,2.089853,0.381944,0.788889,0.130278,13.555754,...,20.255709,15344.5,11693.7,54171.0,1504.694444,275,568,93.8,3117.916742,4970.720308
1,2,37.0766,22.052639,16.547500,73.497083,2.072184,0.344444,0.718056,0.170556,13.678102,...,20.623318,15877.9,11914.2,52917.9,1491.972222,248,517,122.8,5779.277750,9208.189375
2,1,47.2005,21.771667,16.786944,75.555556,2.747222,0.355556,0.781944,0.120278,13.357698,...,21.468948,15675.6,12086.6,54400.0,1978.000000,256,563,86.6,791.432858,1333.557258
3,1,47.3739,20.734306,15.819861,75.873889,2.363272,0.377778,0.837500,0.107778,13.590111,...,20.276167,14928.7,11390.3,54629.2,1701.555556,272,603,77.6,2934.870167,4677.423125
4,1,44.9871,21.710972,16.732222,75.667778,2.523187,0.356944,0.752778,0.095139,13.828215,...,20.732416,15631.9,12047.2,54480.8,1816.694444,257,542,68.5,4805.097617,7620.721658
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,1,74.3736,20.150833,15.310278,76.240278,2.629051,0.415278,0.848611,0.218194,19.136724,...,14.166283,14508.6,11023.4,54893.0,1892.916667,299,611,157.1,13358.500900,11729.418411
143,1,82.0096,20.150833,15.310278,76.240278,2.629051,0.415278,0.848611,0.218194,9.548787,...,18.004157,14508.6,11023.4,54893.0,1892.916667,299,611,157.1,6795.649295,14399.740150
144,1,50.1381,20.150833,15.310278,76.240278,2.629051,0.415278,0.848611,0.218194,12.523602,...,17.252178,14508.6,11023.4,54893.0,1892.916667,299,611,157.1,7254.873860,11434.259833
145,1,73.5072,20.248333,15.631806,77.112500,2.642747,0.412500,0.848611,0.185278,17.679281,...,15.699848,14578.8,11254.9,55521.0,1902.777778,297,611,133.4,12298.577130,12884.937338
146,1,49.7811,20.248333,15.631806,77.112500,2.642747,0.412500,0.848611,0.185278,12.083719,...,17.218818,14578.8,11254.9,55521.0,1902.777778,297,611,133.4,7132.674290,11481.784733

In [50]:
# Read out data

xdat_LX.to_csv('/Users/jilliancheck/Library/CloudStorage/OneDrive-MichiganStateUniversity/Documents/Work/White mold/Modeling/jupyter notebooks/!Finalizing - 2024/Unprocessed data for HPCC/x_dat_LX_HPCC.csv', index=False)
ydat_LX.to_csv('/Users/jilliancheck/Library/CloudStorage/OneDrive-MichiganStateUniversity/Documents/Work/White mold/Modeling/jupyter notebooks/!Finalizing - 2024/Unprocessed data for HPCC/y_dat_LX_HPCC.csv', index=False)